In [2]:
import numpy as np

# 1. Create a 3x3x3 array with random values

In [4]:
x=np.random.random((3,3,3))
x

array([[[0.16562033, 0.23820316, 0.12527899],
        [0.26274835, 0.33858298, 0.12932307],
        [0.57745654, 0.86460177, 0.45296476]],

       [[0.46263927, 0.20431293, 0.52152479],
        [0.06429315, 0.276261  , 0.5618551 ],
        [0.40952861, 0.29296748, 0.57837657]],

       [[0.5316353 , 0.8058469 , 0.68216862],
        [0.74517041, 0.34694026, 0.63837315],
        [0.01725187, 0.02139877, 0.61684938]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [26]:
print("Checkerboard pattern:")
x=np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x



Checkerboard pattern:


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [32]:
x=np.random.random((5,5))
print("The original matrix:")
print(x)
xmax,xmin = x.max(), x.min()
x=x-xmin/xmax-xmin
print("Normalized matrix:")
print(x)

The original matrix:
[[0.51871149 0.08148365 0.98635282 0.53396068 0.51584364]
 [0.52869666 0.37252925 0.55442206 0.20930182 0.13729685]
 [0.61554716 0.18735413 0.43822086 0.04781679 0.88253983]
 [0.45199978 0.75694435 0.16442206 0.9875318  0.68811746]
 [0.6803616  0.70412617 0.95391915 0.14660026 0.11645304]]
Normalized matrix:
[[ 0.42247419 -0.01475365  0.89011552  0.43772338  0.41960634]
 [ 0.43245936  0.27629195  0.45818476  0.11306452  0.04105955]
 [ 0.51930986  0.09111683  0.34198356 -0.04842051  0.78630253]
 [ 0.35576249  0.66070706  0.06818476  0.8912945   0.59188016]
 [ 0.5841243   0.60788887  0.85768185  0.05036296  0.02021574]]


# 5.  How to find common values between two arrays?

In [35]:
array1=([10,4,6,12,3,8])
array2=([4,13,12,3,19])
print("Array1:", array1)
print("Array2:", array2)
print("common values between two arrays:")
array3=np.intersect1d(array1,array2)
print(array3)

Array1: [10, 4, 6, 12, 3, 8]
Array2: [4, 13, 12, 3, 19]
common values between two arrays:
[ 3  4 12]


# 6.How to get the dates of yesterday, today and tomorrow?

In [40]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday date:", yesterday)
today = np.datetime64('today', 'D')
print("Today's date:", today)
Tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's date", Tomorrow)

Yesterday date: 2020-07-27
Today's date: 2020-07-28
Tomorrow's date 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [43]:
x=np.random.randint(0,2,6)
print("Array1", x)
y=np.random.randint(0,2,6)
print("Array2", y)
array_equal=np.allclose(x,y)
print(array_equal)

Array1 [1 1 0 0 0 1]
Array2 [1 1 0 1 1 1]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [45]:
x=np.random.random(10)
print("Random matrix", x)
x[x.argmax()] = 0
print("Maximum values replaced by 0:")
print(x)

Random matrix [0.21594388 0.15786674 0.78434364 0.18538507 0.20208615 0.48718113
 0.78795259 0.85196938 0.96598101 0.2475693 ]
Maximum values replaced by 0:
[0.21594388 0.15786674 0.78434364 0.18538507 0.20208615 0.48718113
 0.78795259 0.85196938 0.         0.2475693 ]


# 9. How to print all the values of an array?

In [10]:
import numpy as np
my_array = np.arange(1001)
np.set_printoptions(threshold=np.inf)
print(my_array)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

# 10.Subtract the mean of each row of a matrix

In [50]:
x=np.random.rand(5,3)
print("Original matrix")
print(x)
y = x-x.mean(axis=1, keepdims=True)
print("The output:")
print(y)

Original matrix
[[0.60644869 0.55263642 0.38470854]
 [0.94465659 0.4346875  0.65046982]
 [0.73006436 0.31452883 0.32077382]
 [0.31721696 0.17682842 0.67308844]
 [0.29885491 0.34559881 0.57411604]]
The output:
[[ 0.09185081  0.03803853 -0.12988934]
 [ 0.26805195 -0.24191714 -0.02613482]
 [ 0.27494202 -0.14059351 -0.13434852]
 [-0.07182765 -0.21221619  0.28404383]
 [-0.10733501 -0.06059111  0.16792612]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [58]:
x=np.random.random((3,5))
print("Input matrix:")
print(x)
y=x+1
print("The output matrix:")
print(y)

Input matrix:
[[0.82989737 0.69846289 0.16073069 0.15001781 0.64423433]
 [0.59328133 0.9000081  0.85702349 0.15459395 0.99677997]
 [0.46022506 0.11490642 0.98183759 0.3348631  0.26266565]]
The output matrix:
[[1.82989737 1.69846289 1.16073069 1.15001781 1.64423433]
 [1.59328133 1.9000081  1.85702349 1.15459395 1.99677997]
 [1.46022506 1.11490642 1.98183759 1.3348631  1.26266565]]


# 12.How to get the diagonal of a dot product?

In [32]:
x=np.random.random((3,3))
print("Input matrix:\n")
print(x)
d = (x * x).sum(axis=0)
print("\nDiagonal of a product:")
d

Input matrix:

[[0.09815399 0.50946779 0.1064791 ]
 [0.07779888 0.92733896 0.26288723]
 [0.41182389 0.98598704 0.85383032]]

Diagonal of a product:


array([0.18528579, 2.09168541, 0.8094737 ])

# 13.How to find the most frequent value in an array?

In [66]:
x=np.random.randint(0,10,5)
print("Input:")
print(x)
y = np.bincount(x).argmax()
print("Most frequent value in an array:")
print(y)

Input:
[7 6 3 5 6]
Most frequent value in an array:
6


# 14.How to get the n largest values of an array

In [70]:
x=np.arange(10)
np.random.shuffle(x)
print("Input matrix", x)
n=1
print("Largest value of an array:")
print(x[np.argsort(x)[-n:]])

Input matrix [2 0 6 9 1 5 4 7 3 8]
Largest value of an array:
[9]


# 15.How to create a record array from a regular array?

In [74]:
x1=["Rupa", "Devi","Malar"]
x2=["Red","black","White"]
x3=[25, 31, 30]
result=np.core.records.fromarrays([x1,x2,x3], names="a,b,c")
print(result[0])
print(result[1])
print(result[2])

('Rupa', 'Red', 25)
('Devi', 'black', 31)
('Malar', 'White', 30)
